---
title: "260216_erm1_peaks"
author: "Erin Osborne Nishimura"
date: "2026-02-16"
output: 
  html_document:
    toc: true
    toc_depth: 4
---

## load libraries
```{r setup, echo = TRUE, warning = FALSE, message=FALSE}
library(tidyverse)
library(gridExtra)
library(data.table)

```

## Import the data that was outputted from the new macro:

```{r macroimport, echo = TRUE, warning = FALSE, message = FALSE}

# import the data
control_1 <- read.table(file = "01_input/2025-03-13_1033_datafile_for_220914_0uM_Noco_wNT002_Rep1.txt", header = FALSE, sep = "\t")
control_2 <- read.table(file = "01_input/2026-3-13_0121_datafile_for_231112_0uM_Noco_wNT002_Rep2.txt", header = FALSE, sep = "\t")

test_1 <- read.table(file = "01_input/2026-03-14_0622_datafile_for_220914_150uM_Noco_wNT002_Rep1.txt", header = FALSE, sep = "\t")
test_2 <- read.table(file = "01_input/2026-03-14_0624_datafile_for_230210_150uM_Noco_wNT002_Rep2.txt", header = FALSE, sep = "\t")
test_3 <- read.table(file = "01_input/2026-03-14_0928_datafile_for_231112_150uM_Noco_wNT002_Rep3.txt", header = FALSE, sep = "\t")
test_4 <- read.table(file = "01_input/2026-03-14_0934_datafile_for_231114_150uM_Noco_wNT002_Rep4.txt", header = FALSE, sep = "\t")



# test its dimensions
dim(control_1)
dim(control_2)
dim(test_1)
dim(test_2)
dim(test_3)
dim(test_4)

# Rename the column names
col_times <- paste(rep(1:333), sep = "")
colnames(control_1) <- c("file", "channel", col_times)
colnames(control_2) <- c("file", "channel", col_times)
colnames(test_1) <- c("file", "channel", col_times)
colnames(test_2) <- c("file", "channel", col_times)
colnames(test_3) <- c("file", "channel", col_times)
colnames(test_4) <- c("file", "channel", col_times)

# Check that the dimensions remain unchanged
dim(control_1)
dim(control_2)
dim(test_1)
dim(test_2)
dim(test_3)
dim(test_4)


control_1[1:7,1:8]
control_2[1:9,1:8]
test_1[1:9,1:8]
test_2[1:9,1:8]
test_3[1:9,1:8]
test_4[1:9,1:8]

```

## Create annotation columns

```{r annotationcolumns, echo = TRUE, warning = FALSE, message = FALSE}

# Extract out the salient information from the filename and pivot the data longer - "permed" version
control_1_exp <- control_1[2:dim(control_1)[1],] %>%
  separate_wider_delim(file, delim = "_", names = c("date", NA, "strain", "conc", NA, "embryoID", NA, NA)) %>%
  pivot_longer(cols = `1`:`333`, names_to = "xpoint", values_to = "intensity") %>%
  mutate(unique_id = paste(date, strain, conc, embryoID, channel, sep = "_"))

test_1_exp <- test_1[2:dim(test_1)[1],1:335] %>%
  separate_wider_delim(file, delim = "_", names = c("date", NA, "strain", "conc", NA, "embryoID", NA, NA)) %>%
  pivot_longer(cols = `1`:`333`, names_to = "xpoint", values_to = "intensity") %>%
  mutate(unique_id = paste(date, strain, conc, embryoID, channel, sep = "_"))

# Extract out the salient information from the filename and pivot the data longer
control_2_exp <- control_2[2:dim(control_2)[1],1:335] %>%
  separate_wider_delim(file, delim = "_", names = c("date", "strain", "conc", NA, "embryoID", NA, NA)) %>%
  pivot_longer(cols = `1`:`333`, names_to = "xpoint", values_to = "intensity") %>%
  mutate(unique_id = paste(date, strain, conc, embryoID, channel, sep = "_"))

test_2_exp <- test_2[2:dim(test_2)[1],1:335] %>%
  separate_wider_delim(file, delim = "_", names = c("date", "strain", "conc", NA, "embryoID", NA, NA)) %>%
  pivot_longer(cols = `1`:`333`, names_to = "xpoint", values_to = "intensity") %>%
  mutate(unique_id = paste(date, strain, conc, embryoID, channel, sep = "_"))

test_3_exp <- test_3[2:dim(test_3)[1],1:335] %>%
  separate_wider_delim(file, delim = "_", names = c("date", "strain", "conc", NA, "embryoID", NA, NA)) %>%
  pivot_longer(cols = `1`:`333`, names_to = "xpoint", values_to = "intensity") %>%
  mutate(unique_id = paste(date, strain, conc, embryoID, channel, sep = "_"))

test_4_exp <- test_4[2:dim(test_4)[1],1:335] %>%
  separate_wider_delim(file, delim = "_", names = c("date", "strain", "conc", NA, "embryoID", NA, NA)) %>%
  pivot_longer(cols = `1`:`333`, names_to = "xpoint", values_to = "intensity") %>%
  mutate(unique_id = paste(date, strain, conc, embryoID, channel, sep = "_"))


# Add in the timepoints

addInTimepoints <- function(tibble) {
  timepoints <- as.vector(unlist(control_1[1,3:335]))
  repnumb = dim(tibble)[1]/333
  tibble::add_column(tibble, timepoints = rep(timepoints,repnumb), .after = "xpoint")
}

control_1_plustime <- addInTimepoints(control_1_exp)
control_2_plustime <- addInTimepoints(control_2_exp)
test_1_plustime <- addInTimepoints(test_1_exp)
test_2_plustime <- addInTimepoints(test_2_exp)
test_3_plustime <- addInTimepoints(test_3_exp)
test_4_plustime <- addInTimepoints(test_4_exp)

# check it
control_1_plustime[330:340,]
control_2_plustime[330:340,]
test_1_plustime[330:340,]
test_2_plustime[330:340,]
test_3_plustime[330:340,]
test_4_plustime[330:340,]


# Merge the datasets together 
nocodazole_data_total <- rbind(control_1_plustime, control_2_plustime, test_1_plustime, test_2_plustime, test_3_plustime, test_4_plustime)

# Plot it - all samples
ggplot(data = nocodazole_data_total, aes(x = timepoints, y = intensity, group = c(unique_id))) +
  geom_line(aes(colour = unique_id))+
  facet_wrap(~ channel + conc)+
  guides(color = "none")+
  theme_bw()

# Plot it - all samples
ggplot(data = nocodazole_data_total, aes(x = timepoints, y = intensity)) +
  geom_line(aes(colour = unique_id))+
  facet_wrap(~ channel + conc)+
  theme_bw()

```

## Align the erm-1 channel info

```{r splitmerge, echo = TRUE, warning = TRUE, message = TRUE}
colnames(nocodazole_data_total)
# Split out channel 2
channel_2_only <- nocodazole_data_total %>%
  filter(channel == "ch2" & conc == "0uM")
unique(channel_2_only$embryoID, channel_2_only$date)
# Split out channel 1
channel_1_only <- nocodazole_data_total %>%
  filter(channel == "ch1" | conc == "150uM")

# Check that everything worked
dim(nocodazole_data_total)
dim(channel_2_only)
dim(channel_1_only)

# Align by finding max per variable and adjusting row_id

channel_2_dt <- as.data.table(channel_2_only)
channel_2_only
channel_2_dt$xpoint <- as.integer(channel_2_dt$xpoint)
channel_2_dt[, aligned_row := xpoint - (which.max(intensity) - 1), by = unique_id]
channel_2_dt
channel2_dcast <- dcast(channel_2_dt, strain + aligned_row ~ unique_id, value.var = "intensity")

channel2_dcast
dim(channel2_dcast)

# Create align rows for channel 1
channel_1_dt <- as.data.table(channel_1_only)
channel_1_dt$xpoint <- as.integer(channel_1_dt$xpoint)

# Create an aligned row for channel 1
dim(channel_1_dt)[1]
head(channel_1_dt)
iterations = dim(channel_1_dt)[1]/333
aligned_row = rep(-166:166, iterations)
length(aligned_row)
channel_1_dt <- cbind(channel_1_dt, aligned_row)
channel1_dcast <- dcast(channel_1_dt, strain + aligned_row ~ unique_id, value.var = "intensity")


dim(channel1_dcast)


# Merge back together
# Pivot long - ch2
colnames(channel2_dcast)
ch2_align_long <- channel2_dcast %>%
  pivot_longer(cols = (`220914_wNT002_0uM_09_ch2`:`231112_wNT002_0uM_07_ch2`), names_to = "unique_id", values_to = "intensity")

# pivot long - ch1
colnames(channel1_dcast)
ch1_align_long <- channel1_dcast %>%
  pivot_longer(cols = (`220914_wNT002_0uM_09_ch1`:`231114_wNT002_150uM_03_ch2`), names_to = "unique_id", values_to = "intensity")

# Check that all the colnames and data types match
colnames(ch2_align_long)
colnames(ch1_align_long)
str(ch2_align_long)
str(ch1_align_long)
ch1_align_long$aligned_row <- as.numeric(ch1_align_long$aligned_row )

# Merge back together
total_align_long <- rbind(ch2_align_long, ch1_align_long)

```

## re-arrange the dataset and calculate the means 

```{r meanplot, echo = TRUE, warning = FALSE, message = FALSE}

# Normalize the data by dividing by the embryo-specific mean
nocodazole_norm_total <- total_align_long %>%
  separate_wider_delim(unique_id, delim = "_", names = c("date", NA, "conc", "embryoID", "channel")) %>%
  group_by(date, embryoID, channel, conc) %>%
  mutate(normalized_intensity = intensity / mean(intensity, na.rm = TRUE))
table(nocodazole_norm_total$channel, nocodazole_norm_total$conc)

nocodazole_norm_total

# Separate out the unique identifier info, then pivot sider
noco_wide_by_sample <- nocodazole_norm_total %>%
  pivot_wider(names_from = c(date, embryoID, channel, conc), 
            values_from = normalized_intensity,
            id_cols = c(strain, aligned_row))


# Second Try - Separate out the unique identifier info, then pivot sider
noco_wide_by_sample <- nocodazole_norm_total %>%
  pivot_wider(names_from = c(date, embryoID), 
            values_from = normalized_intensity,
            id_cols = c(strain, aligned_row, conc, channel))



colnames(noco_wide_by_sample)
# Play around with mean, medium, and sum:
noco_wide_with_stats <- noco_wide_by_sample %>%
  rowwise() %>%
  mutate(sum_signal = sum(c_across(`220914_09`:`231114_03`))) %>%
  mutate(mean_signal = mean(c_across(`220914_09`:`231114_03`), na.rm = TRUE)) %>%
  mutate(median_signal = median(c_across(`220914_09`:`231114_03`), na.rm = TRUE)) %>%
  mutate(sd_signal = sd(c_across(`220914_09`:`231114_03`), na.rm = TRUE))




colnames(noco_wide_with_stats)

noco_wide_with_range <- noco_wide_with_stats %>%
  rowwise() %>%
  mutate(ymeanmax = sum(mean_signal, sd_signal) ) %>%
  mutate(ymeanmin = sum(mean_signal, -sd_signal)) 

colnames(noco_wide_with_range)



colnames(noco_wide_with_range)
str(noco_wide_with_range)



colorselection = c("#000000", "#2189ce")

# Plot split by Nocodazole concentration
a <- ggplot(data = noco_wide_with_range, aes(x = aligned_row, y = mean_signal, group = interaction(channel, conc)))+
  geom_line(aes(color=channel))+
  scale_color_manual(values = colorselection, aesthetics = c("colour", "fill"), labels = c("set-1 mRNA", "erm-1 mRNA"))+
  geom_ribbon(aes(ymin = ymeanmin, ymax = ymeanmax, fill=channel), alpha = 0.2, ) +
  facet_wrap(~ conc)+
  theme_bw()

a


pdf(file = "03_outputPlots/260315_erm_set3_nocodazole.pdf", width = 4, height = 3)

a

dev.off()
colorselection = c("#2189ce", "#000000")
channel.labs <- c("set-3 mRNA", "erm-1 mRNA")
names(channel.labs) <- c("ch1", "ch2")


# Plot split by transcript
b <- ggplot(data = noco_wide_with_range, aes(x = aligned_row, y = mean_signal, group = interaction(channel, conc)))+
  geom_line(aes(color=conc))+
  scale_color_manual(values = colorselection, aesthetics = c("colour", "fill"), labels = c("0 uM Nocodazole", "150 uM Nocodazole"))+
  geom_ribbon(aes(ymin = ymeanmin, ymax = ymeanmax, fill=conc), alpha = 0.2, ) +
  facet_wrap(~ channel, labeller = labeller(channel = channel.labs))+
  theme_bw()

b


pdf(file = "03_outputPlots/260315_erm_set3_nocodazole_bytranscript.pdf", width = 4, height = 3)

b

dev.off()

```

